In [1]:

import pandas as pd
import requests
import zipfile
from io import BytesIO

# Download the original Online Retail II dataset
url = "https://archive.ics.uci.edu/static/public/502/online+retail+ii.zip"

response = requests.get(url, timeout=120)
response.raise_for_status()

print("Dataset downloaded successfully!")

# Open the ZIP file
with zipfile.ZipFile(BytesIO(response.content)) as z:
    files = z.namelist()
    print("Files found:", files)

    # Find the Excel file inside the ZIP
    excel_file = next(
        f for f in files if f.lower().endswith(".xlsx")
    )

    # Load the first worksheet
    with z.open(excel_file) as file:
        df = pd.read_excel(file, sheet_name=0)

# Display the dataset
print("\nDataset loaded successfully!")
print("Shape:", df.shape)
display(df.head(10))

Dataset downloaded successfully!
Files found: ['online_retail_II.xlsx']

Dataset loaded successfully!
Shape: (525461, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom

In [2]:

import pandas as pd
import requests
import zipfile
from io import BytesIO
from google.colab import files

# Download the original dataset
url = "https://archive.ics.uci.edu/static/public/502/online+retail+ii.zip"

response = requests.get(url, timeout=180)
response.raise_for_status()

# Extract and read Excel file
with zipfile.ZipFile(BytesIO(response.content)) as z:
    excel_file = next(
        f for f in z.namelist()
        if f.lower().endswith(".xlsx")
    )

    with z.open(excel_file) as f:
        df = pd.read_excel(f, sheet_name=0)

# Save as CSV
csv_path = "/content/Online_Retail_II.csv"
df.to_csv(csv_path, index=False, encoding="utf-8-sig")

print("CSV created successfully!")
print("Rows and columns:", df.shape)
print("File size (MB):", round(
    __import__("os").path.getsize(csv_path) / (1024 * 1024), 2
))

# Download CSV to your laptop
files.download(csv_path)

CSV created successfully!
Rows and columns: (525461, 8)
File size (MB): 44.64

In [3]:

import pandas as pd

# Load the uploaded CSV file
file_path = "/content/Online_Retail_II.csv"

df = pd.read_csv(
    file_path,
    encoding="ISO-8859-1",
    on_bad_lines="warn"
)

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset loaded successfully!
Rows and columns: (525461, 8)

Column names:
['ï»¿Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

,ï»¿Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:

# Step 1: Clean column names
df.columns = (
    df.columns
    .str.replace("ï»¿", "", regex=False)
    .str.replace("\ufeff", "", regex=False)
    .str.strip()
)

# Step 2: Verify the column names
print("Corrected columns:")
print(df.columns.tolist())

# Step 3: Check invoice values
print("\nSample invoice values:")
print(df["Invoice"].head(10).tolist())

Corrected columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Sample invoice values:
['489434', '489434', '489434', '489434', '489434', '489434', '489434', '489434', '489435', '489435']

In [5]:

# Convert columns to correct data types

df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    dayfirst=True,
    errors="coerce"
)

df["Quantity"] = pd.to_numeric(
    df["Quantity"],
    errors="coerce"
)

df["Price"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)

df["Customer ID"] = pd.to_numeric(
    df["Customer ID"],
    errors="coerce"
).astype("Int64")

# Check the results
print("Updated data types:")
print(df.dtypes)

print("\nMissing values after conversion:")
print(df[["InvoiceDate", "Quantity", "Price", "Customer ID"]].isnull().sum())

display(df.head())

Updated data types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             Int64
Country                object
dtype: object

Missing values after conversion:
InvoiceDate    307243
Quantity            0
Price               0
Customer ID    107927
dtype: int64

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-01-12 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-01-12 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-01-12 07:45:00,1.25,13085,United Kingdom

In [6]:

# STEP 7: Identify data quality issues

# 1. Cancelled invoices usually start with C
cancelled_invoices = df["Invoice"].astype(str).str.startswith("C")

# 2. Negative quantities (often returns)
negative_quantity = df["Quantity"] < 0

# 3. Invalid or zero prices
invalid_price = df["Price"].isna() | (df["Price"] <= 0)

# 4. Missing customer IDs
missing_customer = df["Customer ID"].isna()

print("Total rows:", len(df))
print("Cancelled invoice rows:", cancelled_invoices.sum())
print("Negative quantity rows:", negative_quantity.sum())
print("Missing or non-positive price rows:", invalid_price.sum())
print("Missing Customer IDs:", missing_customer.sum())
print("Duplicate rows:", df.duplicated().sum())

Total rows: 525461
Cancelled invoice rows: 10206
Negative quantity rows: 12326
Missing or non-positive price rows: 3690
Missing Customer IDs: 107927
Duplicate rows: 6866

In [7]:

# Keep the original df unchanged
clean_df = df.copy()

# Identify cancelled invoices
is_cancelled = clean_df["Invoice"].astype(str).str.startswith("C")

# Keep rows with valid customer, date, quantity and price
valid_rows = (
    clean_df["Customer ID"].notna()
    & clean_df["InvoiceDate"].notna()
    & clean_df["Quantity"].notna()
    & clean_df["Price"].notna()
    & (clean_df["Quantity"] > 0)
    & (clean_df["Price"] > 0)
    & (~is_cancelled)
)

clean_df = clean_df.loc[valid_rows].copy()

print("Original rows:", len(df))
print("Rows retained for purchase analysis:", len(clean_df))
print("Rows excluded:", len(df) - len(clean_df))

display(clean_df.head())

Original rows: 525461
Rows retained for purchase analysis: 167043
Rows excluded: 358418

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-01-12 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-01-12 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-01-12 07:45:00,1.25,13085,United Kingdom

In [8]:

import pandas as pd

# Reference date: one day after the last purchase date
reference_date = clean_df["InvoiceDate"].max().normalize() + pd.Timedelta(days=1)

# Calculate revenue for each transaction line
clean_df["Revenue"] = clean_df["Quantity"] * clean_df["Price"]

# Calculate RFM for each customer
rfm = clean_df.groupby("Customer ID").agg(
    Recency=("InvoiceDate", lambda x: (reference_date - x.max().normalize()).days),
    Frequency=("Invoice", "nunique"),
    Monetary=("Revenue", "sum")
).reset_index()

# Display results
print("Reference date:", reference_date.date())
print("Total customers analyzed:", len(rfm))
display(rfm.head(10))

Reference date: 2010-12-12
Total customers analyzed: 2961

   Customer ID  Recency  Frequency  Monetary
0        12346      255          3     72.05
1        12347      153          1    711.79
2        12352        1          1    143.75
3        12356       31          2   3212.40
4        12358      159          2   1697.93
5        12359       63          3   1649.76
6        12360        1          1    690.79
7        12361       98          2    212.15
8        12362      699          1    130.00
9        12369      131          1    348.32

In [9]:

# Assign scores from 1 to 5 using quintiles

# Recency: lower days = better score
rfm["R_Score"] = pd.qcut(
    rfm["Recency"].rank(method="first"),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

# Frequency: more orders = better score
rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

# Monetary: higher spending = better score
rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

# Combine scores into one RFM score
rfm["RFM_Score"] = (
    rfm["R_Score"].astype(str)
    + rfm["F_Score"].astype(str)
    + rfm["M_Score"].astype(str)
)

display(rfm.head(10))

,Customer ID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score
0,12346,255,3,72.05,2,4,1,241
1,12347,153,1,711.79,3,1,4,314
2,12352,1,1,143.75,5,1,1,511
3,12356,31,2,3212.40,5,3,5,535
4,12358,159,2,1697.93,2,3,5,235
5,12359,63,3,1649.76,4,4,5,445
6,12360,1,1,690.79,5,1,4,514
7,12361,98,2,212.15,3,3,2,332
8,12362,699,1,130.00,1,1,1,111
9,12369,131,1,348.32,3,1,2,312

In [10]:

# Assign business-friendly customer segments

def assign_segment(row):
    R = row["R_Score"]
    F = row["F_Score"]
    M = row["M_Score"]

    if R >= 4 and F >= 4 and M >= 4:
        return "Champions"
    elif R >= 3 and F >= 4:
        return "Loyal Customers"
    elif R >= 4 and F <= 2:
        return "Recent Customers"
    elif R <= 2 and F >= 3:
        return "At Risk"
    elif R <= 2 and F <= 2:
        return "Hibernating"
    else:
        return "Potential Loyalists"

rfm["Segment"] = rfm.apply(assign_segment, axis=1)

# Count customers in each segment
segment_summary = (
    rfm.groupby("Segment")
    .agg(
        Customers=("Customer ID", "count"),
        Avg_Recency=("Recency", "mean"),
        Avg_Frequency=("Frequency", "mean"),
        Avg_Monetary=("Monetary", "mean"),
        Total_Revenue=("Monetary", "sum")
    )
    .round(2)
    .sort_values("Customers", ascending=False)
    .reset_index()
)

display(segment_summary)

,Segment,Customers,Avg_Recency,Avg_Frequency,Avg_Monetary,Total_Revenue
0,Hibernating,716,316.76,1.00,326.76,233957.35
1,Champions,569,31.19,6.77,3944.73,2244553.77
2,Potential Loyalists,529,92.47,1.43,563.07,297863.47
3,At Risk,468,266.58,2.37,901.15,421739.03
4,Loyal Customers,400,92.03,3.24,960.45,384178.41
5,Recent Customers,279,39.64,1.00,412.06,114964.16

In [11]:

# Export customer-level RFM results
rfm.to_csv("RFM_Customer_Segments.csv", index=False)

# Export segment-level business summary
segment_summary.to_csv("RFM_Segment_Summary.csv", index=False)

print("Files created successfully!")
print("1. RFM_Customer_Segments.csv")
print("2. RFM_Segment_Summary.csv")

Files created successfully!
1. RFM_Customer_Segments.csv
2. RFM_Segment_Summary.csv

In [12]:

import sqlite3
import pandas as pd

# Create an in-memory SQL database
conn = sqlite3.connect(":memory:")

print("SQL database connected successfully!")

SQL database connected successfully!

In [13]:

import pandas as pd
import sqlite3

# Load the customer RFM file
rfm = pd.read_csv("/content/RFM_Customer_Segments.csv")

# Create SQL table
rfm.to_sql("rfm_customers", conn, if_exists="replace", index=False)

print("Customer RFM data loaded into SQL!")
print("Total customers:", len(rfm))
print("Columns:", rfm.columns.tolist())

Customer RFM data loaded into SQL!
Total customers: 2961
Columns: ['Customer ID', 'Recency', 'Frequency', 'Monetary', 'R_Score', 'F_Score', 'M_Score', 'RFM_Score', 'Segment']

In [14]:

query = """
SELECT *
FROM rfm_customers
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

,Customer ID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,12346,255,3,72.05,2,4,1,241,At Risk
1,12347,153,1,711.79,3,1,4,314,Potential Loyalists
2,12352,1,1,143.75,5,1,1,511,Recent Customers
3,12356,31,2,3212.40,5,3,5,535,Potential Loyalists
4,12358,159,2,1697.93,2,3,5,235,At Risk
5,12359,63,3,1649.76,4,4,5,445,Champions
6,12360,1,1,690.79,5,1,4,514,Recent Customers
7,12361,98,2,212.15,3,3,2,332,Potential Loyalists
8,12362,699,1,130.00,1,1,1,111,Hibernating
9,12369,131,1,348.32,3,1,2,312,Potential Loyalists

In [15]:

query = """
SELECT *
FROM rfm_customers
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

,Customer ID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,12346,255,3,72.05,2,4,1,241,At Risk
1,12347,153,1,711.79,3,1,4,314,Potential Loyalists
2,12352,1,1,143.75,5,1,1,511,Recent Customers
3,12356,31,2,3212.40,5,3,5,535,Potential Loyalists
4,12358,159,2,1697.93,2,3,5,235,At Risk
5,12359,63,3,1649.76,4,4,5,445,Champions
6,12360,1,1,690.79,5,1,4,514,Recent Customers
7,12361,98,2,212.15,3,3,2,332,Potential Loyalists
8,12362,699,1,130.00,1,1,1,111,Hibernating
9,12369,131,1,348.32,3,1,2,312,Potential Loyalists

In [16]:

query = """
SELECT
    Segment,
    COUNT(*) AS Total_Customers
FROM rfm_customers
GROUP BY Segment
ORDER BY Total_Customers DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

               Segment  Total_Customers
0          Hibernating              716
1            Champions              569
2  Potential Loyalists              529
3              At Risk              468
4      Loyal Customers              400
5     Recent Customers              279

In [17]:

query = """
SELECT
    Segment,
    COUNT(*) AS Total_Customers,
    ROUND(SUM(Monetary), 2) AS Total_Revenue,
    ROUND(AVG(Monetary), 2) AS Avg_Revenue_Per_Customer
FROM rfm_customers
GROUP BY Segment
ORDER BY Total_Revenue DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

,Segment,Total_Customers,Total_Revenue,Avg_Revenue_Per_Customer
0,Champions,569,2244553.77,3944.73
1,At Risk,468,421739.03,901.15
2,Loyal Customers,400,384178.41,960.45
3,Potential Loyalists,529,297863.47,563.07
4,Hibernating,716,233957.35,326.76
5,Recent Customers,279,114964.16,412.06

In [18]:

query = """
SELECT
    [Customer ID],
    Recency,
    Frequency,
    Monetary,
    Segment
FROM rfm_customers
ORDER BY Monetary DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
display(result)

   Customer ID  Recency  Frequency   Monetary    Segment
0        18102        8         39  181661.55  Champions
1        14156        3         30   99983.56  Champions
2        14646        9         30   91077.49  Champions
3        15061        1         50   61051.06  Champions
4        14911        1         77   58581.98  Champions
5        13694        4         42   54823.98  Champions
6        15838        2         10   37242.80  Champions
7        17511        7         17   33606.24  Champions
8        16029        8         29   28542.50  Champions
9        16754        8         13   28230.77  Champions

In [19]:

query = """
SELECT
    Segment,
    COUNT(*) AS Total_Customers,
    ROUND(AVG(Recency), 2) AS Avg_Recency,
    ROUND(AVG(Frequency), 2) AS Avg_Frequency,
    ROUND(AVG(Monetary), 2) AS Avg_Monetary
FROM rfm_customers
GROUP BY Segment
ORDER BY Avg_Monetary DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

,Segment,Total_Customers,Avg_Recency,Avg_Frequency,Avg_Monetary
0,Champions,569,31.19,6.77,3944.73
1,Loyal Customers,400,92.03,3.24,960.45
2,At Risk,468,266.58,2.37,901.15
3,Potential Loyalists,529,92.47,1.43,563.07
4,Recent Customers,279,39.64,1.00,412.06
5,Hibernating,716,316.76,1.00,326.76

In [20]:

query = """
SELECT
    COUNT(*) AS Total_Customers,
    COUNT(DISTINCT Segment) AS Total_Segments
FROM rfm_customers;
"""
display(pd.read_sql_query(query, conn))

   Total_Customers  Total_Segments
0             2961               6

In [21]:

query = """
SELECT Segment, COUNT(*) AS Total_Customers
FROM rfm_customers
GROUP BY Segment
ORDER BY Total_Customers DESC;
"""
display(pd.read_sql_query(query, conn))

               Segment  Total_Customers
0          Hibernating              716
1            Champions              569
2  Potential Loyalists              529
3              At Risk              468
4      Loyal Customers              400
5     Recent Customers              279

In [22]:

query = """
SELECT
    Segment,
    COUNT(*) AS Total_Customers,
    ROUND(SUM(Monetary), 2) AS Total_Revenue,
    ROUND(AVG(Monetary), 2) AS Avg_Monetary,
    ROUND(AVG(Recency), 2) AS Avg_Recency,
    ROUND(AVG(Frequency), 2) AS Avg_Frequency
FROM rfm_customers
GROUP BY Segment
ORDER BY Total_Revenue DESC;
"""
display(pd.read_sql_query(query, conn))

,Segment,Total_Customers,Total_Revenue,Avg_Monetary,Avg_Recency,Avg_Frequency
0,Champions,569,2244553.77,3944.73,31.19,6.77
1,At Risk,468,421739.03,901.15,266.58,2.37
2,Loyal Customers,400,384178.41,960.45,92.03,3.24
3,Potential Loyalists,529,297863.47,563.07,92.47,1.43
4,Hibernating,716,233957.35,326.76,316.76,1.00
5,Recent Customers,279,114964.16,412.06,39.64,1.00

In [23]:

query = """
SELECT
    [Customer ID],
    Recency,
    Frequency,
    Monetary,
    Segment
FROM rfm_customers
ORDER BY Monetary DESC
LIMIT 10;
"""
display(pd.read_sql_query(query, conn))

   Customer ID  Recency  Frequency   Monetary    Segment
0        18102        8         39  181661.55  Champions
1        14156        3         30   99983.56  Champions
2        14646        9         30   91077.49  Champions
3        15061        1         50   61051.06  Champions
4        14911        1         77   58581.98  Champions
5        13694        4         42   54823.98  Champions
6        15838        2         10   37242.80  Champions
7        17511        7         17   33606.24  Champions
8        16029        8         29   28542.50  Champions
9        16754        8         13   28230.77  Champions

In [24]:

query = """
SELECT
    [Customer ID],
    Recency,
    Frequency,
    Monetary,
    Segment
FROM rfm_customers
WHERE Segment = 'At Risk'
ORDER BY Monetary DESC
LIMIT 20;
"""
display(pd.read_sql_query(query, conn))

    Customer ID  Recency  Frequency  Monetary  Segment
0         17850      219         74  24368.64  At Risk
1         14028      159          3  10396.50  At Risk
2         12497      223          2   5205.40  At Risk
3         12477      215          2   5035.40  At Risk
4         12949      245          4   4963.72  At Risk
5         14895      159          8   4797.02  At Risk
6         17589      162          5   4678.99  At Risk
7         17940      640          1   4380.00  At Risk
8         15980      187          4   4194.82  At Risk
9         15823      303          3   3882.17  At Risk
10        16732      161          3   3783.89  At Risk
11        15270      162          6   3068.36  At Risk
12        16938      216          3   2980.48  At Risk
13        12633      187          2   2905.48  At Risk
14        15260      159         12   2870.31  At Risk
15        15023      214          5   2847.26  At Risk
16        14607      224          3   2791.71  At Risk
17        12744      186          3   2784.82  At Risk
18        15950      253          3   2708.73  At Risk
19        16984      159          2   2687.28  At Risk

In [25]:

query = """
SELECT
    COUNT(*) AS Champions_Count,
    ROUND(SUM(Monetary), 2) AS Champions_Revenue,
    ROUND(AVG(Frequency), 2) AS Avg_Purchases,
    ROUND(AVG(Recency), 2) AS Avg_Recency
FROM rfm_customers
WHERE Segment = 'Champions';
"""
display(pd.read_sql_query(query, conn))

   Champions_Count  Champions_Revenue  Avg_Purchases  Avg_Recency
0              569         2244553.77           6.77        31.19

In [26]:

# Export segment-wise analysis
segment_analysis = pd.read_sql_query("""
SELECT
    Segment,
    COUNT(*) AS Total_Customers,
    ROUND(SUM(Monetary), 2) AS Total_Revenue,
    ROUND(AVG(Monetary), 2) AS Avg_Monetary,
    ROUND(AVG(Recency), 2) AS Avg_Recency,
    ROUND(AVG(Frequency), 2) AS Avg_Frequency
FROM rfm_customers
GROUP BY Segment
ORDER BY Total_Revenue DESC;
""", conn)

segment_analysis.to_csv(
    "/content/SQL_Segment_Analysis.csv",
    index=False
)

# Export top customers
top_customers = pd.read_sql_query("""
SELECT [Customer ID], Recency, Frequency, Monetary, Segment
FROM rfm_customers
ORDER BY Monetary DESC
LIMIT 100;
""", conn)

top_customers.to_csv(
    "/content/SQL_Top_100_Customers.csv",
    index=False
)

print("Both CSV files created successfully!")
print("1. SQL_Segment_Analysis.csv")
print("2. SQL_Top_100_Customers.csv")

Both CSV files created successfully!
1. SQL_Segment_Analysis.csv
2. SQL_Top_100_Customers.csv

In [27]:

from google.colab import files

files.download("/content/SQL_Segment_Analysis.csv")
files.download("/content/SQL_Top_100_Customers.csv")

In [28]:

query = """
SELECT
    Segment,
    COUNT(*) AS Total_Customers,
    ROUND(SUM(Monetary), 2) AS Total_Revenue
FROM rfm_customers
GROUP BY Segment
ORDER BY Total_Revenue DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

               Segment  Total_Customers  Total_Revenue
0            Champions              569     2244553.77
1              At Risk              468      421739.03
2      Loyal Customers              400      384178.41
3  Potential Loyalists              529      297863.47
4          Hibernating              716      233957.35
5     Recent Customers              279      114964.16

In [29]:

query = """
SELECT
    [Customer ID],
    Recency,
    Frequency,
    ROUND(Monetary, 2) AS Monetary,
    Segment
FROM rfm_customers
ORDER BY Monetary DESC
LIMIT 10;
"""

top_customers = pd.read_sql_query(query, conn)
display(top_customers)

   Customer ID  Recency  Frequency   Monetary    Segment
0        18102        8         39  181661.55  Champions
1        14156        3         30   99983.56  Champions
2        14646        9         30   91077.49  Champions
3        15061        1         50   61051.06  Champions
4        14911        1         77   58581.98  Champions
5        13694        4         42   54823.98  Champions
6        15838        2         10   37242.80  Champions
7        17511        7         17   33606.24  Champions
8        16029        8         29   28542.50  Champions
9        16754        8         13   28230.77  Champions

In [31]:

top_customers.to_csv(
    "SQL_Top_10_Customers.csv",
    index=False
)

from google.colab import files
files.download("SQL_Top_10_Customers.csv")